### PR TITLE
FACES-3134 Enable javax.faces.component.UIInput.ALWAYS_PERFORM_VALIDATION_WHEN_REQUIRED_IS_TRUE by default (correct param-name)

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
bp to 3.x and 2.x <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
Merged, thank you. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by stiemannkj1** [comment]
@ngriffin7a, shouldn't this also be backported to `1.x`?

**Comment by ngriffin7a** [comment]
@stiemannkj1 No, see https://github.com/liferay/liferay-faces-bridge-impl/commit/f12261163dac81158d8bd90fe53ffc98a822a736

**Comment by stiemannkj1** [comment]
Thanks, I will add that to my JSFSPEC-1433 tester (presuming that JSF 1.2 depends on a version of Servlet that doesn't support `web-fragment.xml`).

**Pull request merged**
