### PR TITLE
FACES-3238 Util's PORTLET_API incorrectly reports Portlet 2.1 API version as 1.0 when running in Liferay 7.0 GA5 causing BridgeDependencyVerifier error message(also replaced Java 1.5 ServiceFinder with Java 1.6 ServiceLoader in order to remove unnecessary compat code)

### PR DESCRIPTION
**Pull request by stiemannkj1**
@ngriffin7a, please merge this to `1.x` **only**.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
Removing methods will cause a minor version bump. Let's talk about it on Monday.

**Comment by stiemannkj1** [comment]
@ngriffin7a, as far as I know, I only removed test methods and private inner classes, so no minor bump should be necessary.

\- Kyle

**Comment by stiemannkj1** [comment]
@ngriffin7a, can you re-review and merge this or should I just push this myself?

**Comment by ngriffin7a** [comment]
@stiemannkj1 I will review soon.

**Comment by ngriffin7a** [comment]
Merged, thank you. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
