### PR TITLE
FACES-2664 Reduce JspAdapterFactory API make it consistent with other Factories (remove JspWriterWrapper)

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a, please backport to `2.x` as well.

**Comment by stiemannkj1** [comment]
@ngriffin7a, I will send a PR for `1.x`.

**Comment by ngriffin7a** [comment]
@stiemannkj1 I was able to backport the removal of JspWriterWrapper.java to the 1.x branch. See: a271037f5d72eb708133c6db2243e983b3e416aa

**Comment by ngriffin7a** [comment]
Merged into master (3.x) and backported to 2.x and 1.x. Thank you.

**Pull request merged**
