### PR TITLE
FACES-2966 Netbeans auto completion fails for Liferay Faces components

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
TODO
Before this is merged, I need to look into a better solution (potentially using [`Classloader.getParent()`](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b27/java/lang/ClassLoader.java#ClassLoader.getParent%28%29)).

Other relevant links:
- http://hg.netbeans.org/main/file/c5c2557edd5c/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/facelets/FaceletsLibrarySupport.java#l322
- http://docs.oracle.com/javase/6/docs/api/java/lang/ClassLoader.html#getParent()
- https://issues.liferay.com/browse/FACES-2966

**Comment by stiemannkj1** [comment]
TODO

I've thought of an alternative solution (which will allow for the removal of Netbeans specific code):

Use maven to copy the service files to a location different than **`META-INF/services`** (perhaps **`META-INF/resource/services`** or something like that) so that Netbeans doesn't ignore it. Then access the file there (as a last resort) if we don't find any valid implementations elsewhere (which should never happen in production code):

```
if (loggerFactoryImpl == null) {

    // FACES-2966 Netbeans auto completion fails for Liferay Faces components
    try {
        URL resource = LoggerFactory.class.getResource("/META-INF/resources/services/" + LoggerFactory.class.getName());
        InputStream inputStream = resource.openStream();
        InputStreamReader inputStreamReader = new InputStreamReader(inputStream, "UTF-8");
        BufferedReader bufferedReader = new BufferedReader(inputStreamReader);
        String className = bufferedReader.readLine();
        Class<?> clazz = Class.forName(className);
        loggerFactoryImpl = clazz.newInstance();
    catch (Exception e) {
        // do nothing
    }
    finally {
        if (loggerFactoryImpl == null) {
            throw new RuntimeException("Unable locate service for " + LoggerFactory.class.getName(), e);
        }
    }
}
```

**Comment by ngriffin7a** [comment]
This PR was accidentally merged on Jan 12, 2017 but then was reverted.

**Comment by stiemannkj1** [comment]
Different PR sent for the same issue here: https://github.com/liferay/liferay-faces-util/pull/67

@ngriffin7a, unfortunately I was unable to use `ClassLoader.getParent()` to workaround this issue (as mentioned [in the comment above](https://github.com/liferay/liferay-faces-util/pull/66#issuecomment-264026771)).

**Pull request merged**
